// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkWmoc54SfG4bOWOiO1NsIGcPYaCCFq_s',
    appId: '1:1001421776018:android:61fcf28a5cca9586f8f24b',
    messagingSenderId: '1001421776018',
    projectId: 'cecos-hub',
    storageBucket: 'cecos-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkDd5sZjCULBJKBfzhOyqU-qt7xh2D_qk',
    appId: '1:1001421776018:ios:b6baacbb67faf54df8f24b',
    messagingSenderId: '1001421776018',
    projectId: 'cecos-hub',
    storageBucket: 'cecos-hub.firebasestorage.app',
    androidClientId: '1001421776018-e1a2ca5u6ie3691uo39rar6sht8f1li2.apps.googleusercontent.com',
    iosClientId: '1001421776018-0uti4i6fo7ljurbiopl8e03uli1tl9i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cecosHub',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwiOIkiAOPg7BpSPSgeofpjStuTi6lZvE',
    appId: '1:1001421776018:web:60e1019eb0cbcc90f8f24b',
    messagingSenderId: '1001421776018',
    projectId: 'cecos-hub',
    authDomain: 'cecos-hub.firebaseapp.com',
    storageBucket: 'cecos-hub.firebasestorage.app',
    measurementId: 'G-DEL4QFLSBE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkDd5sZjCULBJKBfzhOyqU-qt7xh2D_qk',
    appId: '1:1001421776018:ios:b6baacbb67faf54df8f24b',
    messagingSenderId: '1001421776018',
    projectId: 'cecos-hub',
    storageBucket: 'cecos-hub.firebasestorage.app',
    androidClientId: '1001421776018-e1a2ca5u6ie3691uo39rar6sht8f1li2.apps.googleusercontent.com',
    iosClientId: '1001421776018-0uti4i6fo7ljurbiopl8e03uli1tl9i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cecosHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwiOIkiAOPg7BpSPSgeofpjStuTi6lZvE',
    appId: '1:1001421776018:web:2fb61158c1f9414ff8f24b',
    messagingSenderId: '1001421776018',
    projectId: 'cecos-hub',
    authDomain: 'cecos-hub.firebaseapp.com',
    storageBucket: 'cecos-hub.firebasestorage.app',
    measurementId: 'G-MWPML38613',
  );

}